### PR TITLE
With automated login with test account

### PR DESCRIPTION
**Pull request by maskaravivek**
I have created a test account on beta server with the following credentials: 

Username: TestCommonsApp
Password: CommonsApp

### CODE REVIEW

**Comment by domdomegg** [comment]
I'm concerned about was having credentials publicly accessible, as a malicious user could mess up the test e.g. by changing the password, or uploading content which results in the test user being banned.

We could just take the risk though I think the ideal case would be having these credentials stored securely on Travis like the APK signing keys.

**Comment by maskaravivek** [comment]
> I'm concerned about was having credentials publicly accessible, as a malicious user could mess up the test e.g. by changing the password, or uploading content which results in the test user being banned.
> 
> We could just take the risk though I think the ideal case would be having these credentials stored securely on Travis like the APK signing keys.

Hmm, I forgot about this bit. Let me change the password and put it securely on Travis. The only issue would be that anyone running the tests locally would have to use their own credentials.

**Comment by maskaravivek** [comment]
@domdomegg I have made the changes.

**Comment by domdomegg** [comment]
Nice. Probably worth changing the password as the old commits on this PR are still public.

**Comment by maskaravivek** [comment]
> Nice. Probably worth changing the password as the old commits on this PR are still public.

Yup, I had changed the password. :)

**Pull request merged**
